name: Build & Push All Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      # ------------------------------------------------------------
      # Login once â€“ used for all pushes
      # ------------------------------------------------------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ------------------------------------------------------------
      # AssetRegistry SERVICE
      # ------------------------------------------------------------
      - name: Build User Asset Image
        run: |
          docker build -t ghcr.io/wasantha99/assetregistry:latest ./src/Services/AssetRegistry

      - name: Push User Audit Image
        run: |
          docker push ghcr.io/wasantha99/assetregistry:latest

      # ------------------------------------------------------------
      # AuditCompliance SERVICE
      # ------------------------------------------------------------
      # - name: Build User Audit Image
      #   run: |
      #     docker build -t ghcr.io/wasantha99/auditcompliance:latest ./src/Services/AuditCompliance

      # - name: Push User Audit Image
      #   run: |
      #     docker push ghcr.io/wasantha99/auditcompliance:latest

      # ------------------------------------------------------------
      # IdentityAccess SERVICE
      # ------------------------------------------------------------
      - name: Build Order Identity Image
        run: |
          docker build -t ghcr.io/wasantha99/identityaccess:latest ./src/Services/IdentityAccess

      - name: Push Order Identity Image
        run: |
          docker push ghcr.io/wasantha99/identityaccess:latest

      # ------------------------------------------------------------
      # MaintenanceScheduler SERVICE
      # ------------------------------------------------------------
      - name: Build Payment Service Image
        run: |
          docker build -t ghcr.io/wasantha99/maintenancescheduler:latest ./src/Services/MaintenanceScheduler

      - name: Push Payment Service Image
        run: |
          docker push ghcr.io/wasantha99/maintenancescheduler:latest

      # ------------------------------------------------------------
      # Notification SERVICE
      # ------------------------------------------------------------
      - name: Build Notification Service Image
        run: |
          docker build -t ghcr.io/wasantha99/notification:latest ./src/Services/Notification

      - name: Push Notification Service Image
        run: |
          docker push ghcr.io/wasantha99/notification:latest
