name: Build & Push All Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ------------------------------------------------------------
      # Login once â€“ used for all pushes
      # ------------------------------------------------------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ------------------------------------------------------------
      # AssetRegistry SERVICE
      # ------------------------------------------------------------
      - name: Build User Service Image
        run: |
          docker build -t ghcr.io/wasantha99/assetregistry:latest ./src/Services/AssetRegistry

      - name: Push User Service Image
        run: |
          docker push ghcr.io/wasantha99/assetregistry:latest

      # ------------------------------------------------------------
      # AuditCompliance SERVICE
      # ------------------------------------------------------------
      - name: Build User Service Image
        run: |
          docker build -t ghcr.io/assetcore/auditcompliance:latest ./src/Services/AuditCompliance

      - name: Push User Service Image
        run: |
          docker push ghcr.io/assetcore/auditcompliance:latest

      # ------------------------------------------------------------
      # IdentityAccess SERVICE
      # ------------------------------------------------------------
      - name: Build Order Service Image
        run: |
          docker build -t ghcr.io/assetcore/identityaccess:latest ./src/Services/IdentityAccess

      - name: Push Order Service Image
        run: |
          docker push ghcr.io/assetcore/identityaccess:latest

      # ------------------------------------------------------------
      # MaintenanceScheduler SERVICE
      # ------------------------------------------------------------
      - name: Build Payment Service Image
        run: |
          docker build -t ghcr.io/assetcore/maintenancescheduler:latest ./src/Services/MaintenanceScheduler

      - name: Push Payment Service Image
        run: |
          docker push ghcr.io/assetcore/maintenancescheduler:latest

      # ------------------------------------------------------------
      # Notification SERVICE
      # ------------------------------------------------------------
      - name: Build Gateway Service Image
        run: |
          docker build -t ghcr.io/assetcore/notification:latest ./src/Services/Notification

      - name: Push Gateway Service Image
        run: |
          docker push ghcr.io/assetcore/notification:latest
