name: AssetRegistry - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/AssetRegistry/**"
      - ".github/workflows/assetregistry.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "AssetRegistry"
      service_path: "./src/Services/AssetRegistry"
      image_name: "assetregistry"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
