name: AssetRegistry - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/AssetRegistry/**"
      - /assetregistry.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "AssetRegistry"
      dockerfile_path: "./src/Services/AssetRegistry/Dockerfile"
      image_name: "assetregistry"
      image_tag: v1.0.${{ github.run_number }}
