name: AuditCompliance - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/AuditCompliance/**"
      - ".github/workflows/auditcompliance.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "AuditCompliance"
      service_path: "./src/Services/AuditCompliance"
      image_name: "auditcompliance"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
