name: AuditCompliance - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/AuditCompliance/**"
      - ".github/workflows/auditcompliance.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "AuditCompliance"
      dockerfile_path: "./src/Services/AuditCompliance/Dockerfile"
      image_name: "auditcompliance"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
