name: IdentityAccess - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/IdentityAccess/**"
      - "workflows/identityaccess.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "IdentityAccess"
      dockerfile_path: "./src/Services/IdentityAccess/DockerFile"
      image_name: "identityaccess"
      image_tag: v1.0.${{ github.run_number }}
