name: IdentityAccess - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/IdentityAccess/**"
      - ".github/workflows/identityaccess.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "IdentityAccess"
      service_path: "./src/Services/IdentityAccess"
      image_name: "identityaccess"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
