name: MaintenanceScheduler - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/MaintenanceScheduler/**"
      - ".github/workflows/maintenancescheduler.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "MaintenanceScheduler"
      dockerfile_path: "./src/Services/MaintenanceScheduler/Dockerfile"
      image_name: "maintenancescheduler"
    secrets:
      DOCKER_TOKEN: ${{ secrets.CJ_GHCR_TOKEN }}
