name: Notification - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/Notification/**"
      - "/notification.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "Notification"
      dockerfile_path: "./src/Services/Notification/Dockerfile"
      image_name: "notification"
      image_tag: v1.0.${{ github.run_number }}
