name: Notification - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/Notification/**"
      - ".github/workflows/notification.yml"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "Notification"
      dockerfile_path: "Services/Notification/Dockerfile"
      image_name: "notification"
