name: Notification - Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "src/Services/Notification/**"

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: "Notification"
      service_path: "./src/Services/Notification"
      image_name: "notification"
